### ISSUE TITLE
Getting 'TransportListenerBindings' exception on trying to do OPC Reverse connect from OPC UA Client program.

### ISSUE THREAD

**Issue by aravinds4uAll** [OPCFoundation/UA-.NETStandard-Samples#28]
I have made up the OPC UA Server with Reverse Connect. (Matrikon Dispatcher). It is able to do reverse connection with the Matrikon dispatcher client tool.

Tried the same OPC Client scenario with ComplexClient project in the client machine but met with the below error.

Please let me know what should be set for the ReverseConnectUri.

     ReverseConnectManager reverseConnectManager = null;
     if (ReverseConnectUri != null)
     {
         // start the reverse connection manager
         reverseConnectManager = new ReverseConnectManager();
         reverseConnectManager.AddEndpoint(**ReverseConnectUri**);
         reverseConnectManager.StartService(config);
     }
Getting the below TransportListenerBindings exception at OPC UA Client with reverse connection.

opc.tcp://10.157.55.140:56000System.AggregateException: One or more errors occurred. (The type initializer for 'Opc.Ua.Bindings.TransportListenerBindings' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'Opc.Ua.Bindings.TransportListenerBindings' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Opc.Ua.Bindings.TcpListener.Dispose(Boolean disposing)
at Opc.Ua.Bindings.TransportListenerBindings.IsTransportListenerType(Type systemType)
at System.Linq.Enumerable.WhereArrayIterator1.MoveNext() at Opc.Ua.Bindings.TransportListenerBindings..cctor() --- End of inner exception stack trace --- at Opc.Ua.Bindings.TransportListenerBindings.GetTransportListener(String uriScheme) at Opc.Ua.ReverseConnectHost.CreateListener(Uri url, EventHandler1 OnConnectionWaiting, EventHandler1 OnConnectionStatusChanged) at Opc.Ua.Client.ReverseConnectManager.AddEndpointInternal(Uri endpointUrl, Boolean configEntry) at Opc.Ua.Client.ReverseConnectManager.AddEndpoint(Uri endpointUrl) at NetCoreConsoleClient.MySampleClient.ConsoleSampleClient() in C:\Users\Administrator\source\repos\NetCoreComplexClient\Program.cs:line 279 --- End of inner exception stack trace --- at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
at NetCoreConsoleClient.MySampleClient.Run() in C:\Users\Administrator\source\repos\NetCoreComplexClient\Program.cs:line 203
---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'Opc.Ua.Bindings.TransportListenerBindings' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Opc.Ua.Bindings.TcpListener.Dispose(Boolean disposing)
at Opc.Ua.Bindings.TransportListenerBindings.IsTransportListenerType(Type systemType)
at System.Linq.Enumerable.WhereArrayIterator1.MoveNext() at Opc.Ua.Bindings.TransportListenerBindings..cctor() --- End of inner exception stack trace --- at Opc.Ua.Bindings.TransportListenerBindings.GetTransportListener(String uriScheme) at Opc.Ua.ReverseConnectHost.CreateListener(Uri url, EventHandler1 OnConnectionWaiting, EventHandler1 OnConnectionStatusChanged) at Opc.Ua.Client.ReverseConnectManager.AddEndpointInternal(Uri endpointUrl, Boolean configEntry) at Opc.Ua.Client.ReverseConnectManager.AddEndpoint(Uri endpointUrl) at NetCoreConsoleClient.MySampleClient.ConsoleSampleClient() in C:\Users\Administrator\source\repos\NetCoreComplexClient\Program.cs:line 279<--- opc.tcp://10.157.55.140:56000System.AggregateException: One or more errors occurred. (The type initializer for 'Opc.Ua.Bindings.TransportListenerBindings' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'Opc.Ua.Bindings.TransportListenerBindings' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Opc.Ua.Bindings.TcpListener.Dispose(Boolean disposing) at Opc.Ua.Bindings.TransportListenerBindings.IsTransportListenerType(Type systemType) at System.Linq.Enumerable.WhereArrayIterator1.MoveNext()
at Opc.Ua.Bindings.TransportListenerBindings..cctor()
--- End of inner exception stack trace ---
at Opc.Ua.Bindings.TransportListenerBindings.GetTransportListener(String uriScheme)
at Opc.Ua.ReverseConnectHost.CreateListener(Uri url, EventHandler1 OnConnectionWaiting, EventHandler1 OnConnectionStatusChanged)
at Opc.Ua.Client.ReverseConnectManager.AddEndpointInternal(Uri endpointUrl, Boolean configEntry)
at Opc.Ua.Client.ReverseConnectManager.AddEndpoint(Uri endpointUrl)
at NetCoreConsoleClient.MySampleClient.ConsoleSampleClient()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at NetCoreConsoleClient.MySampleClient.Run() ---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'Opc.Ua.Bindings.TransportListenerBindings' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Opc.Ua.Bindings.TcpListener.Dispose(Boolean disposing) at Opc.Ua.Bindings.TransportListenerBindings.IsTransportListenerType(Type systemType) at System.Linq.Enumerable.WhereArrayIterator1.MoveNext()
at Opc.Ua.Bindings.TransportListenerBindings..cctor()
--- End of inner exception stack trace ---
at Opc.Ua.Bindings.TransportListenerBindings.GetTransportListener(String uriScheme)
at Opc.Ua.ReverseConnectHost.CreateListener(Uri url, EventHandler1 OnConnectionWaiting, EventHandler1 OnConnectionStatusChanged)
at Opc.Ua.Client.ReverseConnectManager.AddEndpointInternal(Uri endpointUrl, Boolean configEntry)
at Opc.Ua.Client.ReverseConnectManager.AddEndpoint(Uri endpointUrl)
at NetCoreConsoleClient.MySampleClient.ConsoleSampleClient()<---
opc.tcp://10.157.55.140:56000

**Comment by mregen** [comment]
fixed in latest nuget
